---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-default
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-default
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
---
{{/* Only create this SA if either SA for config service or SA for resource service is enabled and the correct service is also enabled */}}
{{- if or (and (.Values.resourceService.enabled) (not .Values.resourceService.serviceAccountName)) (and (not .Values.resourceService.enabled) (not .Values.configurationService.serviceAccountName)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-configuration-service
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-configuration-service
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
{{- end }}
---
{{- if not .Values.shipyardController.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-shipyard-controller
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-shipyard-controller
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
{{- end }}
---
{{- if not .Values.secretService.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-secret-service
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-secret-service
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
{{- end }}
---
{{- if not .Values.lighthouseService.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-lighthouse-service
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-lighthouse-service
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
{{- end }}
---
{{- if not .Values.apiService.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-api-service
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-api-service
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
{{- end }}
---
{{- if .Values.webhookService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-webhook-service
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-webhook-service
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-manage-secrets
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-manage-secrets
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-get-secrets
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-get-secrets
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-manage-roles
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-manage-roles
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - get
      - delete
      - update
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-manage-rolebindings
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-manage-rolebindings
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - get
      - delete
      - update
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-read-metadata
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-read-metadata
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-manage-configmaps
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-manage-configmaps
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-delete-bridge-pod
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-delete-bridge-pod
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - delete
      - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-acquire-lease
  labels:
    app.kubernetes.io/name: keptn-acquire-lease
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
    helm.sh/chart: {{ include "control-plane.chart" . }}
rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    resourceNames:
      - "shipyard-controller-dispatcher"
    verbs:
      - get
      - update
      - create

---
{{- if not .Values.lighthouseService.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-lighthouse-service
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-lighthouse-service
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-configmaps
subjects:
  - kind: ServiceAccount
    name: keptn-lighthouse-service
{{- end }}
---
{{- if not .Values.apiService.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-api-service-metadata
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-api-service-metadata
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-read-metadata
subjects:
  - kind: ServiceAccount
    name: keptn-api-service
{{- end }}
---
{{/* Only create this role binding if either SA for config service or SA for resource service is enabled and the correct service is also enabled */}}
{{- if or (and (.Values.resourceService.enabled) (not .Values.resourceService.serviceAccountName)) (and (not .Values.resourceService.enabled) (not .Values.configurationService.serviceAccountName)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-configuration-service-get-secrets
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-configuration-service-get-secrets
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-get-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-configuration-service
{{- end }}
---
{{- if not .Values.shipyardController.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-shipyard-controller-manage-secrets
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-shipyard-controller-manage-secrets
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-shipyard-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-shipyard-controller-acquire-lease
  labels:
    app.kubernetes.io/name: keptn-shipyard-controller-acquire-lease
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
    helm.sh/chart: {{ include "control-plane.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-acquire-lease
subjects:
  - kind: ServiceAccount
    name: keptn-shipyard-controller
{{- end }}
---
{{- if not .Values.secretService.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-secret-service-manage-secrets
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-secret-service-manage-secrets
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-secret-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-secret-service-manage-roles
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-secret-service-manage-roles
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-roles
subjects:
  - kind: ServiceAccount
    name: keptn-secret-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-secret-service-manage-rolebindings
  labels:
    {{ include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/name: keptn-secret-service-manage-secrets
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-rolebindings
subjects:
  - kind: ServiceAccount
    name: keptn-secret-service
{{- end }}
