apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: approval-service
spec:
  selector:
    matchLabels: {{- include "common.labels.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: approval-service
  replicas: 1
  {{- include "keptn.common.update-strategy" . | nindent 2 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
        app.kubernetes.io/component: approval-service
    spec:
      {{- include "keptn.common.pod-security-context" . | nindent 6 }}
      terminationGracePeriodSeconds: {{ .Values.approvalService.gracePeriod | default 120 }}
      serviceAccountName: keptn-default
      containers:
        - name: approval-service
          image: {{ .Values.approvalService.image.repository }}:{{ .Values.approvalService.image.tag | default .Chart.AppVersion }}
          {{- $prestop := .Values.approvalService.preStopHookTime | default 90 | quote -}}
          {{- include "keptn.prestop" $prestop | nindent 10 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.approvalService.resources | nindent 12 }}
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: EVENTBROKER
              value: 'http://localhost:8081/event'
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | default "info" }}
          {{- include "keptn.common.container-security-context" . | nindent 10 }}
          {{- if .Values.approvalService.extraVolumeMounts }}
          volumeMounts:
          {{- include "keptn.tpl-value" ( dict "value" .Values.approvalService.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        - name: distributor
          image: {{ .Values.distributor.image.repository }}:{{ .Values.distributor.image.tag | default .Chart.AppVersion }}
          {{- include "keptn.dist.livenessProbe" . | nindent 10 }}
          {{- include "keptn.dist.readinessProbe" . | nindent 10 }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.distributor.resources | nindent 12 }}
          env:
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.approval.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
          {{- include "keptn.dist.common.env.vars" . | nindent 12 }}
          {{- include "keptn.common.container-security-context" . | nindent 10 }}
        {{- with .Values.approvalService.sidecars }}
        {{- include "keptn.tpl-value" ( dict "value" . "context" $ ) | nindent 8 }}
        {{- end }}
      {{- if .Values.approvalService.extraVolumes }}
      volumes:
      {{- include "keptn.tpl-value" ( dict "value" .Values.approvalService.extraVolumes "context" $) | nindent 8 }}
      {{- end }}
      {{- include "keptn.nodeSelector" (dict "value" .Values.approvalService.nodeSelector "default" .Values.nodeSelector "indent" 6 "context" . )}}
---
apiVersion: v1
kind: Service
metadata:
  name: approval-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: approval-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector: {{- include "common.labels.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: approval-service
