---
# lighthouse-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "keptn.name" . }}
spec:
  selector:
    matchLabels: {{- include "common.labels.selectorLabels" . | nindent 6 }}
  replicas: 1
  {{- include "keptn.common.update-strategy" . | nindent 2 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
        app.kubernetes.io/component: {{ include "keptn.name" . }}
    spec:
      {{- include "keptn.common.pod-security-context" . | nindent 6 }}
      containers:
        - name: lighthouse-service
          image: {{ .Values.lighthouseService.image.repository }}:{{ .Values.lighthouseService.image.tag | default .Chart.AppVersion }}
          {{- $prestop := .Values.lighthouseService.preStopHookTime | default 90 | quote -}}
          {{- include "keptn.prestop" $prestop | nindent 10 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.lighthouseService.resources | nindent 12 }}
          env:
            - name: EVENTBROKER
              value: 'http://localhost:8081/event'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: MONGODB_DATASTORE
              value: 'mongodb-datastore:8080'
            - name: ENVIRONMENT
              value: 'production'
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | default "info" }}
          {{- include "keptn.common.container-security-context" . | nindent 10 }}
          {{- if .Values.lighthouseService.extraVolumeMounts }}
          volumeMounts:
          {{- include "keptn.tpl-value" ( dict "value" .Values.lighthouseService.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        - name: distributor
          image: {{ .Values.distributor.image.repository }}:{{ .Values.distributor.image.tag | default .Chart.AppVersion }}
          {{- include "keptn.dist.livenessProbe" . | nindent 10 }}
          {{- include "keptn.dist.readinessProbe" . | nindent 10 }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.distributor.resources | nindent 12 }}
          env:
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.evaluation.triggered,sh.keptn.event.get-sli.finished,sh.keptn.event.monitoring.configure'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
          {{- include "keptn.dist.common.env.vars" . | nindent 12 }}
          {{- include "keptn.common.container-security-context" . | nindent 10 }}
        {{- with .Values.lighthouseService.sidecars }}
        {{- include "keptn.tpl-value" ( dict "value" . "context" $ ) | nindent 8 }}
        {{- end }}
      {{- if .Values.lighthouseService.extraVolumes }}
      volumes:
      {{- include "keptn.tpl-value" ( dict "value" .Values.lighthouseService.extraVolumes "context" $) | nindent 8 }}
      {{- end }}
      serviceAccountName: keptn-lighthouse-service
      terminationGracePeriodSeconds: {{ .Values.lighthouseService.gracePeriod | default 120 }}
      {{- include "keptn.nodeSelector" (dict "value" .Values.lighthouseService.nodeSelector "default" .Values..nodeSelector "indent" 6 "context" . )}}
---
apiVersion: v1
kind: Service
metadata:
  name: lighthouse-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "keptn.name" . }}
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector: {{- include "common.labels.selectorLabels" . | nindent 4 }}
